site_name: ALADIN-ALPHA
site_url: https://alexe15.github.io/ALADIN.m/
site_description: Project documentation ALADIN-M
site_author: Alexander Engelmann
docs_dir: docs/

repo_name: 'alexe15/ALADIN.m'
repo_url: https://github.com/alexe15/ALADIN.m
edit_uri: ""



theme:
    name: material
    highlightjs: true
    hljs_languages: matlab
    navigation_depth: 1
    features:
      - tabs
      - instant
    palette:
      primary: blue grey
      accent: indigo
#    font:
#      text: Ubuntu
#      code: Ubuntu Mono
nav:
  - Getting Started: index.md
  - The Algorithm: ALADIN.md
  - Code Structure: codeStruct.md
  - Options: options.md
  - Application Examples:
    - Distributed MPC: robotEx.md
    - Reducing Communication: redComm.md
    - Parallel Computing: ParallelExample.md
  - Publications: furtherReading.md

markdown_extensions:
 # - codehilite
  - pymdownx.arithmatex
  - smarty
  - tables
  - toc
  - admonition
  - codehilite:
      linenums: True

plugins:
  - search
  - awesome-pages:
        collapse_single_pages: true

#  - markdownmermaid
      
  

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

  
extra_css:
  - css/extra.css
  