name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
      - name: Install dependencies
        run:  pip3 install mkdocs-mermaid-plugin
      - name: Install dependencies2
        run:  pip3 install mkdocs-awesome-pages-plugin
      - name: Install dependencies3
        run:  pip install mkdocs-awesome-pages-plugin


      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
